version: "3.8"

services:
  request-bin:
    image: request-bin:latest
    container_name: request-bin
    environment:
      DB_URL: postgres://postgres:yourpassword@postgres:5432/postgres?sslmode=disable
    ports:
      - "8080:8080"
  postgres:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:

