### GET health
GET http://localhost:8080/healthz
Accept: application/json

### OPTIONS root
OPTIONS http://localhost:8080/
Accept: application/json

### OPTIONS azure event grid
OPTIONS http://localhost:8080/azure/eventGrid
Accept: application/json

### GET test requestbin
GET http://localhost:8080/bin?queryparams=yup,there,here&moarparams=some;more;params
Accept: application/json
Content-Type: multipart/form-data;boundary=WebAppBoundary


### POST test requestbin
POST http://localhost:8080/bin?queryparams=yup,there,here&moarparams=some;more;params
Accept: application/json
Content-Type: multipart/form-data;boundary=WebAppBoundary

{"somedata":true}

### POST test custom trace path
POST http://localhost:8080/v1/trace
Accept: application/json
Content-Type: multipart/form-data;boundary=WebAppBoundary

{"somedata":true}


### GET test resp code
POST http://localhost:8080/respCode/500
Accept: application/json

{"somedata": true}

### GET requests
GET http://localhost:8080/v1/requests
Accept: application/json

### GET headers by id
GET http://localhost:8080/v1/requests/headers?request_id=0195361a-55c3-76e6-a7bf-0ad0b0fe5a18

### GET headers
GET http://localhost:8080/v1/requests/headers

### GET query params by id
GET http://localhost:8080/v1/requests/queryParams?request_id=0195361a-55c3-76e6-a7bf-0ad0b0fe5a18

### GET query params
GET http://localhost:8080/v1/requests/queryParams