### GET health
GET http://localhost:8080/healthz
Accept: application/json

### OPTIONS root
OPTIONS http://localhost:8080/
Accept: application/json

### OPTIONS azure event grid
OPTIONS http://localhost:8080/azure/eventGrid
Accept: application/json

### GET test requestbin
GET http://localhost:8080/bin?queryparams=yup,there,here&moarparams=some;more;params
Accept: application/json
Content-Type: multipart/form-data;boundary=WebAppBoundary


### POST test requestbin
POST http://localhost:8080/bin?queryparams=yup,there,here&moarparams=some;more;params
Accept: application/json
Content-Type: multipart/form-data;boundary=WebAppBoundary

{"somedata":true}

### POST test custom trace path
POST http://localhost:8080/v1/trace
Accept: application/json
Content-Type: multipart/form-data;boundary=WebAppBoundary

{"somedata":true}


### GET test resp code
POST http://localhost:8080/respCode/500
Accept: application/json

{"somedata": true}

### GET test resp code
POST http://localhost:8080/respCode/400
Accept: application/xml

<?xml version="1.0" encoding="UTF-8"?>
<note>
  <to>Tove</to>
  <from>Jani</from>
  <heading>Reminder</heading>
  <body>Don't forget me this weekend!</body>
</note>

### POST test login
POST localhost:8080/rbv1/login
Content-Type: application/json

{
  "username": "admin",
  "password": "farsos-be-testing"
}

### GET check auth
GET http://localhost:8080/rbv1/checkAuth

### GET requests
GET http://localhost:8080/rbv1/requests
Accept: application/json

### GET requests next token
GET http://localhost:8080/rbv1/requests?next_token='0199fa59-8b6b-7182-b333-6cd5739b269f'&limit=10
Accept: application/json

### GET headers by id
GET http://localhost:8080/rbv1/requests/headers?request_id=0199dee5-f5be-7ac1-b50b-204a770fde67

### GET headers
GET http://localhost:8080/rbv1/requests/headers

### GET query params by id
GET http://localhost:8080/rbv1/requests/queryParams?request_id=0199dee5-f5be-7ac1-b50b-204a770fde67

### GET query params
GET http://localhost:8080/rbv1/requests/queryParams
